version: "3"
services:
  chat-app-backend-dev:
    container_name: chat-app-backend-dev
    image: thomasschafer/chat-app-backend-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
