version: "3"
services:
  login-app:
    container_name: chat-app-backend
    image: thomasschafer/chat-app-backend
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
